FROM alpine:latest
RUN apk --no-cache add ansible curl openssh-client openssh-server
WORKDIR /code/ansible
RUN ssh-keygen -A
COPY ssh/ /code/.ssh/
COPY ssh/id_rsa.pub /code/.ssh/authorized_keys
RUN chmod 600 /code/.ssh/id_rsa
EXPOSE 22 80
CMD ["/usr/sbin/sshd", "-D"]