#!/bin/sh

### BEGIN INIT INFO
# Provides:          traefik
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Traefik at boot time
# Description:       Enable Traefik service
### END INIT INFO

# Path to the Traefik binary
DAEMON=/usr/local/bin/traefik
# Traefik configuration file
CONFIG=/etc/traefik/traefik.yaml
# User to run Traefik
USER=www-data

case "$1" in
  start)
    echo "Starting Traefik"
    start-stop-daemon --start --quiet --background --exec $DAEMON -- -c $CONFIG
    ;;
  stop)
    echo "Stopping Traefik"
    start-stop-daemon --stop --quiet --name traefik
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    if pgrep -x "traefik" > /dev/null
    then
      echo "Traefik is running"
    else
      echo "Traefik is not running"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/traefik {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
